# Generated by Django 5.2.11 on 2026-05-30 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_goodsreceipt_shipment_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.taxcode'),
        ),
    ]
