# Generated by Django 5.2.11 on 2026-05-31 12:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backfill_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('box1_vat_due_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('box2_vat_due_acquisitions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('box3_total_vat_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('box4_vat_reclaimed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('box5_net_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('box6_total_sales_ex_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('box7_total_purchases_ex_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('box8_eu_supplies', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('box9_eu_acquisitions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hmrc_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-period_to'],
                'unique_together': {('tenant', 'period_from', 'period_to')},
            },
        ),
    ]
