# Generated by Django 5.2.11 on 2026-05-31 12:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_inventorymovement_unit_cost_inventorymovement_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ref_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='core.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['received_at', 'id'],
                'indexes': [models.Index(fields=['tenant', 'product', 'qty_remaining'], name='core_invent_tenant__2e6894_idx')],
            },
        ),
    ]
