# Generated by Django 5.2.11 on 2026-06-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_accessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_country',
            field=models.CharField(blank=True, default='United Kingdom', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_country',
            field=models.CharField(blank=True, default='United Kingdom', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_same_as_business',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(blank=True, choices=[('LTD', 'Limited company'), ('SOLE_TRADER', 'Sole trader'), ('PARTNERSHIP', 'Partnership'), ('CHARITY', 'Charity'), ('FRANCHISE', 'Franchise')], max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_payment_terms_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_tenants', to='core.taxcode'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='financial_year_start_month',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='invoice_footer',
            field=models.TextField(blank=True, help_text='Shown at the bottom of invoices and receipts.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trading_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='utr_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vat_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
