# Generated by Django 5.2.11 on 2026-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tenant_address_city_tenant_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
