# Generated by Django 5.2.11 on 2026-06-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userpermissionoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='keep_permissions_on_role_change',
            field=models.BooleanField(default=False),
        ),
    ]
