# Generated by Django 5.2.11 on 2026-06-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_banktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccount',
            name='type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('COGS', 'Cost of goods sold'), ('EXPENSE', 'Expense')], max_length=20),
        ),
    ]
