# Generated by Django 5.2.11 on 2026-06-04 10:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_customerinvoice_sent_at_customerinvoice_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
