# Generated by Django 5.2.11 on 2026-06-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_recurringinvoice_recurringinvoiceline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('RECEIPT', 'Customer receipt'), ('PAYMENT', 'Supplier payment'), ('REFUND', 'Customer refund')], max_length=10),
        ),
    ]
