# Generated by Django 5.2.11 on 2026-06-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_payment_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_housekeeping_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
