# Generated by Django 5.2.11 on 2026-06-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_supplier_address_supplier_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_products', to='core.supplier'),
        ),
    ]
