# Generated by Django 5.2.11 on 2026-06-04 14:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_product_preferred_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('STOCK', 'Stock item'), ('SERVICE', 'Service'), ('NON_STOCK', 'Non-stock item'), ('BUNDLE', 'Bundle / kit'), ('RAW_MATERIAL', 'Raw material'), ('FINISHED_GOOD', 'Finished good')], default='STOCK', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.taxcode'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='track_lots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='track_serial',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='core.productcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'unique_together': {('tenant', 'name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productcategory'),
        ),
    ]
