# Generated by Django 5.2.11 on 2026-06-04 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_product_brand_product_description_product_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIVE', 'Purchase received'), ('SALE', 'Sale fulfilled'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('ADJUSTMENT', 'Manual adjustment'), ('RETURN', 'Return from customer'), ('RETURN_SUPPLIER', 'Return to supplier'), ('DAMAGE', 'Damage'), ('WRITE_OFF', 'Write-off'), ('RESERVATION', 'Reservation'), ('RELEASE', 'Release')], max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('STORE', 'Shop / Store'), ('OFFICE', 'Office'), ('VAN', 'Van'), ('THREEPL', '3PL'), ('POPUP', 'Pop-up location'), ('TRANSIT', 'Transit'), ('RETURNS', 'Returns'), ('QUARANTINE', 'Quarantine')], default='WAREHOUSE', max_length=20),
        ),
    ]
