# Generated by Django 5.2.11 on 2026-06-04 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_from_po_lines(apps, schema_editor):
    """Seed price history from existing submitted/processed PO lines so the
    supplier and product profiles show history that predates this feature."""
    PurchaseOrderLine = apps.get_model("core", "PurchaseOrderLine")
    SupplierPriceHistory = apps.get_model("core", "SupplierPriceHistory")
    seen = set()
    qs = (PurchaseOrderLine.objects
          .exclude(po__status="DRAFT")
          .select_related("po", "po__supplier", "product"))
    for line in qs:
        po = line.po
        if po.supplier_id is None or line.unit_cost is None or line.unit_cost <= 0:
            continue
        key = (po.tenant_id, po.supplier_id, line.product_id, "PO", po.po_number or "")
        if key in seen:
            continue
        seen.add(key)
        SupplierPriceHistory.objects.get_or_create(
            tenant_id=po.tenant_id, supplier_id=po.supplier_id, product_id=line.product_id,
            source="PO", reference=(po.po_number or ""),
            defaults={"unit_cost": line.unit_cost, "currency_code": getattr(po, "currency_code", "GBP") or "GBP",
                      "recorded_at": po.created_at.date()},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_backfill_inventory_adjustment_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(default='GBP', max_length=3)),
                ('source', models.CharField(choices=[('PO', 'Purchase Order'), ('BILL', 'Supplier Bill'), ('MANUAL', 'Manual')], default='PO', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=64, null=True)),
                ('recorded_at', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='core.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
                'unique_together': {('tenant', 'supplier', 'product', 'source', 'reference')},
            },
        ),
        migrations.RunPython(backfill_from_po_lines, noop),
    ]
