# Generated by Django 5.2.11 on 2026-06-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_stockadjustment_credit_note_stockadjustment_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='last_reminder_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='dunning_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='dunning_interval_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
