# Generated by Django 5.2.11 on 2026-06-05 00:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_customerinvoice_last_reminder_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=core.models.expense_receipt_path),
        ),
        migrations.AddField(
            model_name='expense',
            name='reimbursable',
            field=models.BooleanField(default=False),
        ),
    ]
