# Generated by Django 5.2.11 on 2026-06-05 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_expense_approved_at_expense_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx'),
        ),
    ]
