# Generated by Django 5.2.11 on 2026-06-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_customerinvoice_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='holds_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('STORE', 'Shop / Store'), ('OFFICE', 'Office'), ('VAN', 'Van'), ('POPUP', 'Pop-up location'), ('THREEPL', '3PL'), ('STORAGE', 'Storage unit'), ('TRANSIT', 'Transit'), ('RETURNS', 'Returns'), ('QUARANTINE', 'Quarantine')], default='WAREHOUSE', max_length=20),
        ),
    ]
