# Generated by Django 5.2.11 on 2026-06-05 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_bin_inventorymovement_bin_stockadjustment_bin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='is_intercompany',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_intercompany',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InterCompanyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ic_links', to='core.customerinvoice')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ic_links', to='core.expense')),
                ('from_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ic_sales', to='core.tenant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ic_transactions', to='core.companygroup')),
                ('to_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ic_purchases', to='core.tenant')),
            ],
        ),
    ]
