# Generated by Django 5.2.11 on 2026-06-06 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_usersiteaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybalance',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='core.site'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.site'),
        ),
    ]
