# Generated by Django 5.2.11 on 2026-06-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_backfill_stock_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_invoices', to='core.site'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='core.site'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.site'),
        ),
    ]
