# Generated by Django 5.2.11 on 2026-06-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_backfill_document_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('STORE', 'Shop / Store'), ('SHOP_FLOOR', 'Shop floor'), ('BACK_ROOM', 'Back room'), ('COLD_STORAGE', 'Cold storage'), ('OFFICE', 'Office'), ('VAN', 'Delivery van'), ('POPUP', 'Pop-up location'), ('THREEPL', '3PL warehouse'), ('STORAGE', 'Storage room'), ('TRANSIT', 'Transit'), ('RETURNS', 'Returns area'), ('DAMAGED', 'Damaged goods area'), ('QUARANTINE', 'Quarantine')], default='WAREHOUSE', max_length=20),
        ),
    ]
