# Generated by Django 5.2.11 on 2026-06-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.site'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.site'),
        ),
    ]
