# Generated by Django 5.2.11 on 2026-06-06 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_backfill_gl_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.site'),
        ),
    ]
