# Generated by Django 5.2.15 on 2026-06-09 11:33

import django.db.models.deletion
from django.db import migrations, models


def backfill_layer_location(apps, schema_editor):
    """Best-effort assign a location to existing FIFO cost layers.

    Preference order: the location of the matching RECEIVE movement (same
    tenant/product/ref), else the product's sole stock-balance location, else
    the tenant's first location. Without this, the new location-scoped FIFO
    consumption query would never relieve the legacy layers and their value
    would be stranded."""
    InventoryCostLayer = apps.get_model('core', 'InventoryCostLayer')
    InventoryMovement = apps.get_model('core', 'InventoryMovement')
    InventoryBalance = apps.get_model('core', 'InventoryBalance')
    Location = apps.get_model('core', 'Location')

    first_loc_by_tenant = {}

    def first_location(tenant_id):
        if tenant_id not in first_loc_by_tenant:
            loc = Location.objects.filter(tenant_id=tenant_id).order_by('id').first()
            first_loc_by_tenant[tenant_id] = loc.id if loc else None
        return first_loc_by_tenant[tenant_id]

    for layer in InventoryCostLayer.objects.filter(location__isnull=True).iterator():
        loc_id = None
        if layer.ref_type and layer.ref_id:
            mv = (InventoryMovement.objects
                  .filter(tenant_id=layer.tenant_id, product_id=layer.product_id,
                          ref_type=layer.ref_type, ref_id=layer.ref_id, qty_delta__gt=0)
                  .order_by('id').first())
            if mv:
                loc_id = mv.location_id
        if loc_id is None:
            bal_locs = list(InventoryBalance.objects
                            .filter(tenant_id=layer.tenant_id, product_id=layer.product_id)
                            .values_list('location_id', flat=True)[:2])
            if len(bal_locs) == 1:
                loc_id = bal_locs[0]
        if loc_id is None:
            loc_id = first_location(layer.tenant_id)
        if loc_id is not None:
            layer.location_id = loc_id
            layer.save(update_fields=['location'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_emaillog_notification_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycostlayer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='core.location'),
        ),
        migrations.RunPython(backfill_layer_location, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='inventorycostlayer',
            index=models.Index(fields=['tenant', 'product', 'location', 'qty_remaining'], name='core_invent_tenant__f930a0_idx'),
        ),
    ]
