# Generated by Django 5.2.15 on 2026-06-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_inventorycostlayer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='block_negative_stock',
            field=models.BooleanField(default=False),
        ),
    ]
