# Generated by Django 5.2.15 on 2026-06-09 12:21

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def backfill_stable_identity(apps, schema_editor):
    """Assign stable PO-line identities and rebuild received_qty from receipts.

    1. Link every amended clone of a logical line back to its original (v1) line
       via root_line, matching by (PO version chain, product).
    2. Stamp each GoodsReceiptLine.root_line from its po_line's root.
    3. Rebuild received_qty on every PO line from the actual POSTED receipts for
       its stable identity, replacing the old per-version counter (M17)."""
    PurchaseOrder = apps.get_model('core', 'PurchaseOrder')
    PurchaseOrderLine = apps.get_model('core', 'PurchaseOrderLine')
    GoodsReceiptLine = apps.get_model('core', 'GoodsReceiptLine')
    from django.db.models import Sum

    pos = {p.id: p for p in PurchaseOrder.objects.all()}

    def chain_root(po_id):
        """Walk supersedes (new -> old) to the original PO in the chain."""
        seen = set()
        cur = po_id
        while cur is not None and cur not in seen:
            seen.add(cur)
            sup = pos[cur].supersedes_id if cur in pos else None
            if sup is None or sup not in pos:
                return cur
            cur = sup
        return cur

    # Group logical lines by (chain root PO, product); earliest version is root.
    groups = {}
    for line in PurchaseOrderLine.objects.all():
        groups.setdefault((chain_root(line.po_id), line.product_id), []).append(line)
    for glines in groups.values():
        glines.sort(key=lambda l: (pos[l.po_id].version if l.po_id in pos else 0, l.id))
        root = glines[0]
        for l in glines[1:]:
            l.root_line_id = root.id
            l.save(update_fields=['root_line'])

    # Stamp GRN lines with the stable identity.
    for grl in GoodsReceiptLine.objects.select_related('po_line').all():
        grl.root_line_id = grl.po_line.root_line_id or grl.po_line_id
        grl.save(update_fields=['root_line'])

    # Rebuild received_qty cache from POSTED receipts per stable identity.
    totals = {row['root_line_id']: (row['s'] or Decimal('0.00'))
              for row in (GoodsReceiptLine.objects
                          .filter(receipt__status='POSTED')
                          .values('root_line_id')
                          .annotate(s=Sum('qty_received')))}
    for line in PurchaseOrderLine.objects.all():
        stable = line.root_line_id or line.id
        line.received_qty = totals.get(stable, Decimal('0.00'))
        line.save(update_fields=['received_qty'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_tenant_block_negative_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='root_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines_by_root', to='core.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='root_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_versions', to='core.purchaseorderline'),
        ),
        migrations.RunPython(backfill_stable_identity, migrations.RunPython.noop),
    ]
