# Generated by Django 5.2.15 on 2026-06-09 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_po_line_stable_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryIssueCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='lot_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='inventorycostlayer',
            index=models.Index(fields=['tenant', 'product', 'location', 'lot_code', 'qty_remaining'], name='core_invent_tenant__0d99ce_idx'),
        ),
        migrations.AddField(
            model_name='inventoryissuecost',
            name='cost_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_costs', to='core.inventorycostlayer'),
        ),
        migrations.AddField(
            model_name='inventoryissuecost',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_costs', to='core.inventorymovement'),
        ),
        migrations.AddField(
            model_name='inventoryissuecost',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='inventoryissuecost',
            index=models.Index(fields=['tenant', 'movement'], name='core_invent_tenant__38a62f_idx'),
        ),
    ]
