# Generated by Django 5.2.15 on 2026-06-09 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_lot_scoped_costing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCountValuationCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valuation_source', models.CharField(choices=[('LOT_LAYER', 'Lot/serial cost layer'), ('PRODUCT_AVERAGE', 'Product-average fallback')], max_length=20)),
                ('posted_to_current_period', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('correction_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_valuation_corrections', to='core.journalentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('original_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cc_valuation_correction', to='core.inventorymovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('reval_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_reval_for', to='core.inventorymovement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='core_cyclec_tenant__3cf67f_idx')],
            },
        ),
    ]
