# Generated by Django 5.2.15 on 2026-06-09 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_cycle_count_valuation_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoiceline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='customerorderline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='recurringinvoiceline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unitofmeasure'),
        ),
    ]
