# Generated by Django 5.2.15 on 2026-06-09 14:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_line_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransfer',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransferline',
            name='dispatched_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='inventorytransferline',
            name='dispatched_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransferline',
            name='received_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorytransfer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched (in transit)'), ('RECEIVED', 'Received'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
