# Generated by Django 5.2.15 on 2026-06-09 14:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_backfill_inventory_in_transit_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBinBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reserved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='core.bin')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'bin'], name='core_invent_tenant__c092f3_idx')],
                'unique_together': {('tenant', 'product', 'location', 'bin')},
            },
        ),
    ]
