# Generated by Django 5.2.15 on 2026-06-09 16:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_inventory_bin_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=40, null=True)),
                ('scope', models.CharField(choices=[('LOCATION', 'Single location'), ('SITE', 'Whole site')], default='LOCATION', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SNAPSHOTTED', 'Snapshotted'), ('COUNTING', 'Counting'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('blind', models.BooleanField(default=True)),
                ('count_date', models.DateField(default=django.utils.timezone.now)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_takes', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_takes', to='core.location')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_stock_takes', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_takes', to='core.site')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_stock_takes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_takes', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('expected_qty_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variance_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('expected_value_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('variance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('count_status', models.CharField(choices=[('PENDING', 'Pending'), ('COUNTED', 'Counted'), ('STALE', 'Stale (recount)'), ('APPROVED', 'Approved'), ('POSTED', 'Posted')], default='PENDING', max_length=10)),
                ('is_unexpected', models.BooleanField(default=False)),
                ('reason_code', models.CharField(blank=True, max_length=60, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_take_lines', to='core.bin')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_stock_take_lines', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_take_lines', to='core.unitofmeasure')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.stocktakesession')),
            ],
            options={
                'ordering': ['location__name', 'product__sku'],
            },
        ),
        migrations.AddIndex(
            model_name='stocktakesession',
            index=models.Index(fields=['tenant', 'status'], name='core_stockt_tenant__7858d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeline',
            unique_together={('session', 'product', 'location', 'bin', 'lot_code', 'serial_number', 'expiry_date')},
        ),
    ]
