# Generated by Django 5.2.15 on 2026-06-10 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_customerinvoiceline_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnline',
            name='disposition',
            field=models.CharField(choices=[('RESTOCK', 'Restock (sellable)'), ('QUARANTINE', 'Quarantine (inspection hold)'), ('SCRAP', 'Scrap / write-off'), ('REPAIR', 'Repair / refurbish (hold)'), ('RETURN_TO_SUPPLIER', 'Return to supplier (hold)')], default='QUARANTINE', max_length=20),
        ),
        migrations.AddField(
            model_name='returnline',
            name='disposition_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='returnline',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnline',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_return_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnline',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
