# Generated by Django 5.2.15 on 2026-06-10 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_returnline_disposition_returnline_disposition_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnline',
            name='final_disposition',
            field=models.CharField(blank=True, choices=[('RESTOCK', 'Restock (sellable)'), ('QUARANTINE', 'Quarantine (inspection hold)'), ('SCRAP', 'Scrap / write-off'), ('REPAIR', 'Repair / refurbish (hold)'), ('RETURN_TO_SUPPLIER', 'Return to supplier (hold)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='returnline',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnline',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_return_lines', to=settings.AUTH_USER_MODEL),
        ),
    ]
