# Generated by Django 5.2.15 on 2026-06-10 13:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_replenishmentpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='landed_cleared',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
