# Generated by Django 5.2.15 on 2026-06-10 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_supplierinvoice_landed_cleared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorycostlayer',
            index=models.Index(fields=['tenant', 'product', 'location', 'serial_number'], name='core_invent_tenant__395525_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylotbalance',
            index=models.Index(fields=['tenant', 'expiry_date'], name='core_invent_tenant__0f4cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['tenant', 'created_at'], name='core_invent_tenant__a4647f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['tenant', 'product', 'location'], name='core_invent_tenant__092b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['tenant', 'ref_type', 'ref_id'], name='core_invent_tenant__cc77e5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['tenant', 'serial_number'], name='core_invent_tenant__bb07b0_idx'),
        ),
    ]
