# Generated by Django 5.2.15 on 2026-06-10 15:27

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Q


def check_no_duplicate_refs(apps, schema_editor):
    """Fail clearly (without touching data) if duplicate journal references
    already exist in the scope the new constraint covers. Journals are
    accounting history — they are never auto-deleted. If this raises, run the
    pre-migration audit query in the PR/release notes and resolve the duplicates
    manually before re-running migrate.
    """
    JournalEntry = apps.get_model("core", "JournalEntry")
    dupes = (JournalEntry.objects
             .filter(ref_type__isnull=False, ref_id__isnull=False)
             .exclude(ref_type="").exclude(ref_id="")
             .exclude(ref_type="TRANSFER_RECEIPT")
             .values("tenant_id", "ref_type", "ref_id")
             .annotate(n=Count("id")).filter(n__gt=1))
    found = list(dupes[:20])
    if found:
        raise RuntimeError(
            "Cannot add uniq_journal_entry_ref: duplicate (tenant, ref_type, ref_id) "
            f"journal entries already exist. Examples: {found}. "
            "Investigate and resolve manually (do NOT delete accounting history blindly) "
            "then re-run migrate.")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_inventorycostlayer_core_invent_tenant__395525_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_no_duplicate_refs, noop),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('ref_type__isnull', False), models.Q(('ref_type', ''), _negated=True), ('ref_id__isnull', False), models.Q(('ref_id', ''), _negated=True), models.Q(('ref_type', 'TRANSFER_RECEIPT'), _negated=True)), fields=('tenant', 'ref_type', 'ref_id'), name='uniq_journal_entry_ref'),
        ),
    ]
