# Generated by Django 5.2.15 on 2026-06-10 16:19
from django.db import migrations, models
from django.db.models import Window, F
from django.db.models.functions import RowNumber


def backfill_line_no(apps, schema_editor):
    """Give existing BOM lines stable numbers 10, 20, 30... per BOM, ordered by
    id, BEFORE the (bom, line_no) uniqueness constraint is added. Deterministic
    and idempotent for a single forward run; touches only line_no (component,
    qty, uom are never modified)."""
    Line = apps.get_model("core", "BillOfMaterialsLine")
    # Number rows within each BOM by ascending id (Window avoids per-row queries).
    numbered = Line.objects.annotate(
        rn=Window(expression=RowNumber(), partition_by=[F("bom_id")], order_by=F("id").asc())
    )
    updates = []
    for ln, rn in numbered.values_list("id", "rn"):
        updates.append((ln, rn * 10))
    for pk, line_no in updates:
        Line.objects.filter(pk=pk).update(line_no=line_no)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_journalentry_uniq_journal_entry_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterialsline',
            options={'ordering': ['line_no', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterialsline',
            unique_together={('bom', 'component')},
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='line_no',
            field=models.PositiveIntegerField(default=10),
        ),
        # Backfill BEFORE enforcing (bom, line_no) uniqueness, so existing
        # multi-line BOMs (all defaulted to 10) get 10/20/30 and don't collide.
        migrations.RunPython(backfill_line_no, noop),
        migrations.AlterUniqueTogether(
            name='billofmaterialsline',
            unique_together={('bom', 'component'), ('bom', 'line_no')},
        ),
    ]
