# Generated by Django 5.2.15 on 2026-06-13 12:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_billofmaterialsline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='output_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='BillOfMaterialsLinePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='core.billofmaterialsline')),
            ],
            options={
                'ordering': ['reference', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='bom_placement_qty_positive')],
                'unique_together': {('bom_line', 'reference')},
            },
        ),
    ]
