# Generated by Django 5.2.15 on 2026-06-15 17:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_billofmaterials_notes_billofmaterials_output_qty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MRPRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.CharField(max_length=40)),
                ('run_type', models.CharField(choices=[('FULL', 'Full regeneration'), ('NET_CHANGE', 'Net change'), ('SIMULATION', 'Simulation')], default='FULL', max_length=12)),
                ('forecast_version', models.CharField(blank=True, max_length=60)),
                ('planning_start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('planning_end_date', models.DateField(blank=True, null=True)),
                ('include_sales_orders', models.BooleanField(default=True)),
                ('include_forecast', models.BooleanField(default=False)),
                ('include_safety_stock', models.BooleanField(default=True)),
                ('include_transfers', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_EXCEPTIONS', 'Completed with exceptions'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=28)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('site_scope', models.ForeignKey(blank=True, help_text='Blank = all sites', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_runs', to='core.site')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_runs_started', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_runs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MRPPlannedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('BUY', 'Buy'), ('MAKE', 'Make'), ('TRANSFER', 'Transfer'), ('SUBCONTRACT', 'Subcontract')], default='BUY', max_length=12)),
                ('planned_order_number', models.CharField(max_length=40)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('required_date', models.DateField()),
                ('planned_receipt_date', models.DateField(blank=True, null=True)),
                ('planned_release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('REVIEWED', 'Reviewed'), ('FIRMED', 'Firmed'), ('CONVERTED', 'Converted'), ('IGNORED', 'Ignored'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='SUGGESTED', max_length=12)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('RESCHEDULE_IN', 'Reschedule in'), ('RESCHEDULE_OUT', 'Reschedule out'), ('CANCEL', 'Cancel'), ('EXPEDITE', 'Expedite'), ('DEFER', 'Defer')], default='CREATE', max_length=16)),
                ('exception_level', models.CharField(choices=[('NONE', 'None'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='NONE', max_length=8)),
                ('created_work_order_ref', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_planned_orders', to=settings.AUTH_USER_MODEL)),
                ('created_purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_planned_orders', to='core.purchaseorder')),
                ('created_purchase_requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_planned_orders', to='core.purchaserequisition')),
                ('created_transfer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_planned_orders', to='core.inventorytransfer')),
                ('parent_planned_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_orders', to='core.mrpplannedorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_planned_orders', to='core.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_planned_orders', to='core.site')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_planned_orders', to='core.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_planned_orders', to='core.tenant')),
                ('transfer_from_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_planned_transfers_out', to='core.site')),
                ('mrp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_orders', to='core.mrprun')),
            ],
            options={
                'ordering': ['product__sku', 'required_date'],
            },
        ),
        migrations.CreateModel(
            name='MRPException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_code', models.CharField(choices=[('SHORTAGE', 'Shortage'), ('PAST_DUE_DEMAND', 'Past-due demand'), ('PAST_DUE_SUPPLY', 'Past-due supply'), ('RESCHEDULE_IN', 'Reschedule in'), ('RESCHEDULE_OUT', 'Reschedule out'), ('CANCEL_SUPPLY', 'Cancel supply'), ('EXCESS_SUPPLY', 'Excess supply'), ('BELOW_SAFETY_STOCK', 'Below safety stock'), ('MISSING_BOM', 'Missing BOM'), ('MISSING_ROUTING', 'Missing routing'), ('MISSING_SUPPLIER', 'Missing supplier'), ('MISSING_LEAD_TIME', 'Missing lead time'), ('MISSING_UOM_CONVERSION', 'Missing UOM conversion'), ('NON_NETTABLE_STOCK', 'Non-nettable stock'), ('EXPIRED_LOT', 'Expired lot'), ('CAPACITY_OVERLOAD', 'Capacity overload')], max_length=24)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=8)),
                ('message', models.TextField(blank=True)),
                ('recommended_action', models.CharField(blank=True, max_length=255)),
                ('source_document_type', models.CharField(blank=True, max_length=50)),
                ('source_document_id', models.CharField(blank=True, max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mrp_exceptions', to='core.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_exceptions_resolved', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mrp_exceptions', to='core.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_exceptions', to='core.tenant')),
                ('planned_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='core.mrpplannedorder')),
                ('mrp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='core.mrprun')),
            ],
            options={
                'ordering': ['severity', 'product__sku'],
            },
        ),
        migrations.CreateModel(
            name='MRPDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_type', models.CharField(choices=[('SALES_ORDER', 'Sales order'), ('FORECAST', 'Forecast'), ('SAFETY_STOCK', 'Safety stock'), ('WORK_ORDER_COMPONENT', 'Work order component'), ('TRANSFER_REQUEST', 'Transfer request'), ('SERVICE', 'Service / repair')], max_length=24)),
                ('source_document_type', models.CharField(blank=True, max_length=50)),
                ('source_document_id', models.CharField(blank=True, max_length=100)),
                ('source_line_id', models.CharField(blank=True, max_length=100)),
                ('required_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('consumed_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('open_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('priority', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_demands', to='core.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_demands', to='core.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_demands', to='core.tenant')),
                ('mrp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='core.mrprun')),
            ],
            options={
                'ordering': ['product__sku', 'required_date'],
            },
        ),
        migrations.CreateModel(
            name='MRPSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_type', models.CharField(choices=[('ON_HAND', 'On hand'), ('PURCHASE_ORDER', 'Open purchase order'), ('PURCHASE_REQUISITION', 'Open purchase requisition'), ('WORK_ORDER', 'Open work order'), ('TRANSFER_ORDER', 'Open transfer order'), ('IN_TRANSIT', 'In transit'), ('PLANNED_ORDER', 'Planned order')], max_length=24)),
                ('source_document_type', models.CharField(blank=True, max_length=50)),
                ('source_document_id', models.CharField(blank=True, max_length=100)),
                ('source_line_id', models.CharField(blank=True, max_length=100)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('mrp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='core.mrprun')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_supplies', to='core.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_supplies', to='core.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_supplies', to='core.tenant')),
            ],
            options={
                'ordering': ['product__sku', 'receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='ItemSitePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('BUY', 'Buy (purchase)'), ('MAKE', 'Make (manufacture)'), ('TRANSFER', 'Transfer (from another site)'), ('SUBCONTRACT', 'Subcontract'), ('PHANTOM', 'Phantom (blow-through)')], default='BUY', max_length=12)),
                ('safety_stock_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('min_order_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_order_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = no maximum', max_digits=12)),
                ('order_multiple', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Round order up to a multiple of this; 0 = none', max_digits=12)),
                ('fixed_order_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Used when lot sizing = Fixed quantity', max_digits=12)),
                ('period_days', models.PositiveSmallIntegerField(default=0, help_text='Bucket size for Period order quantity')),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0)),
                ('planning_horizon_days', models.PositiveSmallIntegerField(default=90)),
                ('time_fence_days', models.PositiveSmallIntegerField(default=0, help_text='No automatic reschedule/cancel inside this fence')),
                ('lot_sizing_method', models.CharField(choices=[('LOT_FOR_LOT', 'Lot for lot'), ('FIXED_QTY', 'Fixed quantity'), ('MIN_MAX', 'Min / Max'), ('PERIOD_ORDER_QTY', 'Period order quantity')], default='LOT_FOR_LOT', max_length=20)),
                ('yield_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('scrap_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('mrp_enabled', models.BooleanField(default=True)),
                ('include_sales_orders', models.BooleanField(default=True)),
                ('include_forecast', models.BooleanField(default=False)),
                ('include_safety_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_planning_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('default_manufacturing_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_manufacturing_for', to='core.site')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_profiles', to='core.supplier')),
                ('default_transfer_from_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_transfer_source_for', to='core.site')),
                ('planner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_planning_as_planner', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_profiles', to='core.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_planning', to='core.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_site_planning', to='core.tenant')),
            ],
            options={
                'ordering': ['product__sku', 'site__name'],
                'indexes': [models.Index(fields=['tenant', 'site', 'mrp_enabled'], name='core_itemsi_tenant__153d43_idx')],
                'unique_together': {('tenant', 'product', 'site')},
            },
        ),
        migrations.CreateModel(
            name='MRPPegging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegged_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('supply_date', models.DateField(blank=True, null=True)),
                ('shortage_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peggings', to='core.mrpdemand')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_peggings', to='core.tenant')),
                ('planned_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peggings', to='core.mrpplannedorder')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['planned_order'], name='core_mrppeg_planned_7367a6_idx'), models.Index(fields=['demand'], name='core_mrppeg_demand__9083f2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mrprun',
            index=models.Index(fields=['tenant', 'status'], name='core_mrprun_tenant__e32f2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mrprun',
            unique_together={('tenant', 'run_number')},
        ),
        migrations.AddIndex(
            model_name='mrpplannedorder',
            index=models.Index(fields=['mrp_run', 'status'], name='core_mrppla_mrp_run_3f631f_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpplannedorder',
            index=models.Index(fields=['mrp_run', 'source_type'], name='core_mrppla_mrp_run_325b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpplannedorder',
            index=models.Index(fields=['tenant', 'status'], name='core_mrppla_tenant__364c8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mrpplannedorder',
            unique_together={('tenant', 'planned_order_number')},
        ),
        migrations.AddIndex(
            model_name='mrpexception',
            index=models.Index(fields=['mrp_run', 'severity'], name='core_mrpexc_mrp_run_b3b59b_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpexception',
            index=models.Index(fields=['mrp_run', 'exception_code'], name='core_mrpexc_mrp_run_cac49c_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpexception',
            index=models.Index(fields=['mrp_run', 'is_resolved'], name='core_mrpexc_mrp_run_d75ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpdemand',
            index=models.Index(fields=['mrp_run', 'product', 'site'], name='core_mrpdem_mrp_run_0cdcf7_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpdemand',
            index=models.Index(fields=['mrp_run', 'required_date'], name='core_mrpdem_mrp_run_eda9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsupply',
            index=models.Index(fields=['mrp_run', 'product', 'site'], name='core_mrpsup_mrp_run_183443_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsupply',
            index=models.Index(fields=['mrp_run', 'receipt_date'], name='core_mrpsup_mrp_run_c96077_idx'),
        ),
    ]
