# Generated by Django 5.2.15 on 2026-06-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_mrprun_mrpplannedorder_mrpexception_mrpdemand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrpexception',
            name='exception_code',
            field=models.CharField(choices=[('SHORTAGE', 'Shortage'), ('PAST_DUE_DEMAND', 'Past-due demand'), ('PAST_DUE_SUPPLY', 'Past-due supply'), ('RESCHEDULE_IN', 'Reschedule in'), ('RESCHEDULE_OUT', 'Reschedule out'), ('CANCEL_SUPPLY', 'Cancel supply'), ('EXCESS_SUPPLY', 'Excess supply'), ('BELOW_SAFETY_STOCK', 'Below safety stock'), ('MISSING_BOM', 'Missing BOM'), ('MISSING_ROUTING', 'Missing routing'), ('MISSING_SUPPLIER', 'Missing supplier'), ('MISSING_LEAD_TIME', 'Missing lead time'), ('MISSING_UOM_CONVERSION', 'Missing UOM conversion'), ('NON_NETTABLE_STOCK', 'Non-nettable stock excluded'), ('EXPIRED_LOT', 'Expired lot'), ('CAPACITY_OVERLOAD', 'Capacity overload'), ('SALES_ORDER_REQUIRED_DATE_MISSING', 'Sales order required date inferred'), ('PURCHASE_ORDER_DUE_DATE_MISSING', 'Purchase order due date inferred'), ('PAST_DUE_RELEASE', 'Planned release date is in the past'), ('UNSUPPORTED_LOT_SIZING_METHOD', 'Unsupported lot sizing method')], max_length=40),
        ),
    ]
