# Generated by Django 5.2.15 on 2026-06-15 20:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_mrpexception_exception_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mrpplannedorder',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mrpplannedorder',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_planned_orders_converted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisitionline',
            name='mrp_planned_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_lines', to='core.mrpplannedorder'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=40)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('FIRM', 'Firm'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='PLANNED', max_length=12)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.site')),
                ('source_mrp_planned_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.mrpplannedorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mrpplannedorder',
            name='created_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_planned_orders', to='core.workorder'),
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('bom_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.billofmaterialsline')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_materials', to='core.product')),
                ('source_mrp_demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_materials', to='core.mrpdemand')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unitofmeasure')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.workorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'status'], name='core_workor_tenant__86b9b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workorder',
            unique_together={('tenant', 'work_order_number')},
        ),
    ]
