# Generated by Django 5.2.15 on 2026-06-15 21:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_mrpplannedorder_converted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='finished_goods_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quantity_completed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quantity_scrapped',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='workorder',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_released', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wip_material_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='issued_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='issued_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='source_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_materials', to='core.bin'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_materials', to='core.location'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_ISSUED', 'Partially issued'), ('ISSUED', 'Issued'), ('SHORT', 'Short'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=18),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIVE', 'Purchase received'), ('SALE', 'Sale fulfilled'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('ADJUSTMENT', 'Manual adjustment'), ('RETURN', 'Return from customer'), ('RETURN_SUPPLIER', 'Return to supplier'), ('DAMAGE', 'Damage'), ('WRITE_OFF', 'Write-off'), ('RESERVATION', 'Reservation'), ('RELEASE', 'Release'), ('WORK_ORDER_ISSUE', 'Work order material issue'), ('WORK_ORDER_COMPLETION', 'Work order completion')], max_length=24),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('FIRM', 'Firm'), ('RELEASED', 'Released'), ('PARTIALLY_COMPLETED', 'Partially completed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='PLANNED', max_length=20),
        ),
    ]
