# Generated by Django 5.2.15 on 2026-06-16 10:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_inventorymovement_journal_entry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrpexception',
            name='exception_code',
            field=models.CharField(choices=[('SHORTAGE', 'Shortage'), ('PAST_DUE_DEMAND', 'Past-due demand'), ('PAST_DUE_SUPPLY', 'Past-due supply'), ('RESCHEDULE_IN', 'Reschedule in'), ('RESCHEDULE_OUT', 'Reschedule out'), ('CANCEL_SUPPLY', 'Cancel supply'), ('EXCESS_SUPPLY', 'Excess supply'), ('BELOW_SAFETY_STOCK', 'Below safety stock'), ('MISSING_BOM', 'Missing BOM'), ('MISSING_ROUTING', 'Missing routing'), ('MISSING_SUPPLIER', 'Missing supplier'), ('MISSING_LEAD_TIME', 'Missing lead time'), ('MISSING_UOM_CONVERSION', 'Missing UOM conversion'), ('NON_NETTABLE_STOCK', 'Non-nettable stock excluded'), ('EXPIRED_LOT', 'Expired lot'), ('CAPACITY_OVERLOAD', 'Capacity overload'), ('SALES_ORDER_REQUIRED_DATE_MISSING', 'Sales order required date inferred'), ('PURCHASE_ORDER_DUE_DATE_MISSING', 'Purchase order due date inferred'), ('PAST_DUE_RELEASE', 'Planned release date is in the past'), ('UNSUPPORTED_LOT_SIZING_METHOD', 'Unsupported lot sizing method'), ('FORECAST_VERSION_MISSING', 'Forecast version not selected'), ('FORECAST_VERSION_INVALID', 'Forecast version invalid for planning'), ('FORECAST_LINE_OUTSIDE_HORIZON', 'Forecast line outside planning horizon'), ('FORECAST_LINE_INVALID_QTY', 'Forecast line has invalid quantity'), ('UNSUPPORTED_FORECAST_CONSUMPTION_METHOD', 'Unsupported forecast consumption method'), ('FORECAST_UOM_CONVERSION_MISSING', 'Missing forecast UOM conversion'), ('FORECAST_SITE_MISSING', 'Forecast site missing'), ('INVALID_BOM', 'Invalid BOM'), ('BOM_NOT_APPROVED', 'BOM not approved'), ('BOM_NOT_EFFECTIVE', 'BOM not effective'), ('CIRCULAR_BOM', 'Circular BOM'), ('BOM_MAX_DEPTH_EXCEEDED', 'BOM max depth exceeded'), ('MISSING_COMPONENT_PLANNING', 'Missing component planning profile'), ('PHANTOM_BOM_MISSING', 'Phantom item has no BOM'), ('MISSING_TRANSFER_SOURCE_SITE', 'Missing transfer source site'), ('INVALID_TRANSFER_SOURCE_SITE', 'Invalid transfer source site'), ('SOURCE_SITE_SHORTAGE', 'Source site shortage'), ('TRANSFER_LOOP_DETECTED', 'Transfer loop detected'), ('TRANSFER_MAX_DEPTH_EXCEEDED', 'Transfer max depth exceeded'), ('INBOUND_TRANSFER_DUE_DATE_MISSING', 'Inbound transfer due date inferred')], max_length=40),
        ),
        migrations.CreateModel(
            name='ForecastVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('forecast_type', models.CharField(choices=[('BASELINE', 'Baseline'), ('SALES', 'Sales'), ('CUSTOMER', 'Customer'), ('ML', 'Machine learning'), ('MANUAL', 'Manual')], default='BASELINE', max_length=10)),
                ('consumption_method', models.CharField(choices=[('NONE', 'No consumption'), ('SAME_BUCKET', 'Same bucket'), ('FORWARD_BACKWARD_DAYS', 'Forward / backward days')], default='SAME_BUCKET', max_length=24)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_versions_created', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_versions_locked', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_versions', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('bucket_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=8)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('consumed_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('CSV', 'CSV import'), ('ML', 'Machine learning'), ('API', 'API')], default='MANUAL', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_lines', to='core.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_lines', to='core.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_lines', to='core.tenant')),
                ('forecast_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.forecastversion')),
            ],
            options={
                'ordering': ['product__sku', 'forecast_date'],
            },
        ),
        migrations.AddIndex(
            model_name='forecastversion',
            index=models.Index(fields=['tenant', 'status'], name='core_foreca_tenant__83747d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastversion',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='forecastline',
            index=models.Index(fields=['forecast_version', 'product', 'site'], name='core_foreca_forecas_130c01_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastline',
            index=models.Index(fields=['forecast_version', 'forecast_date'], name='core_foreca_forecas_046014_idx'),
        ),
    ]
