# Generated by Django 5.2.15 on 2026-06-16 12:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_mrpexception_exception_code_forecastversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrpexception',
            name='exception_code',
            field=models.CharField(choices=[('SHORTAGE', 'Shortage'), ('PAST_DUE_DEMAND', 'Past-due demand'), ('PAST_DUE_SUPPLY', 'Past-due supply'), ('RESCHEDULE_IN', 'Reschedule in'), ('RESCHEDULE_OUT', 'Reschedule out'), ('CANCEL_SUPPLY', 'Cancel supply'), ('EXCESS_SUPPLY', 'Excess supply'), ('BELOW_SAFETY_STOCK', 'Below safety stock'), ('MISSING_BOM', 'Missing BOM'), ('MISSING_ROUTING', 'Missing routing'), ('MISSING_SUPPLIER', 'Missing supplier'), ('MISSING_LEAD_TIME', 'Missing lead time'), ('MISSING_UOM_CONVERSION', 'Missing UOM conversion'), ('NON_NETTABLE_STOCK', 'Non-nettable stock excluded'), ('EXPIRED_LOT', 'Expired lot'), ('CAPACITY_OVERLOAD', 'Capacity overload'), ('SALES_ORDER_REQUIRED_DATE_MISSING', 'Sales order required date inferred'), ('PURCHASE_ORDER_DUE_DATE_MISSING', 'Purchase order due date inferred'), ('PAST_DUE_RELEASE', 'Planned release date is in the past'), ('UNSUPPORTED_LOT_SIZING_METHOD', 'Unsupported lot sizing method'), ('FORECAST_VERSION_MISSING', 'Forecast version not selected'), ('FORECAST_VERSION_INVALID', 'Forecast version invalid for planning'), ('FORECAST_LINE_OUTSIDE_HORIZON', 'Forecast line outside planning horizon'), ('FORECAST_LINE_INVALID_QTY', 'Forecast line has invalid quantity'), ('UNSUPPORTED_FORECAST_CONSUMPTION_METHOD', 'Unsupported forecast consumption method'), ('FORECAST_UOM_CONVERSION_MISSING', 'Missing forecast UOM conversion'), ('FORECAST_SITE_MISSING', 'Forecast site missing'), ('INVALID_ROUTING', 'Invalid routing'), ('ROUTING_NOT_ACTIVE', 'Routing not active'), ('MISSING_WORK_CENTRE', 'Missing work centre'), ('INVALID_WORK_CENTRE', 'Invalid / inactive work centre'), ('SUBCONTRACT_OPERATION_NOT_SUPPORTED', 'Subcontract operation not supported'), ('ROUTING_DURATION_INVALID', 'Routing duration invalid'), ('INVALID_BOM', 'Invalid BOM'), ('BOM_NOT_APPROVED', 'BOM not approved'), ('BOM_NOT_EFFECTIVE', 'BOM not effective'), ('CIRCULAR_BOM', 'Circular BOM'), ('BOM_MAX_DEPTH_EXCEEDED', 'BOM max depth exceeded'), ('MISSING_COMPONENT_PLANNING', 'Missing component planning profile'), ('PHANTOM_BOM_MISSING', 'Phantom item has no BOM'), ('MISSING_TRANSFER_SOURCE_SITE', 'Missing transfer source site'), ('INVALID_TRANSFER_SOURCE_SITE', 'Invalid transfer source site'), ('SOURCE_SITE_SHORTAGE', 'Source site shortage'), ('TRANSFER_LOOP_DETECTED', 'Transfer loop detected'), ('TRANSFER_MAX_DEPTH_EXCEEDED', 'Transfer max depth exceeded'), ('INBOUND_TRANSFER_DUE_DATE_MISSING', 'Inbound transfer due date inferred')], max_length=40),
        ),
        migrations.CreateModel(
            name='RoutingHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_code', models.CharField(max_length=40)),
                ('revision', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='core.product')),
                ('site', models.ForeignKey(blank=True, help_text='Blank = applies at any site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings', to='core.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='core.tenant')),
            ],
            options={
                'ordering': ['product__sku', 'routing_code'],
            },
        ),
        migrations.CreateModel(
            name='WorkCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('capacity_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=8)),
                ('efficiency_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('calendar_code', models.CharField(blank=True, max_length=40)),
                ('working_days_mask', models.CharField(blank=True, help_text='Optional Mon-Sun mask, e.g. 1111100', max_length=7)),
                ('default_queue_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('default_move_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_centres', to='core.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_centres', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_sequence', models.PositiveIntegerField(default=10)),
                ('operation_name', models.CharField(max_length=120)),
                ('setup_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('run_minutes_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('queue_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('move_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('yield_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('is_subcontract_operation', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.routingheader')),
                ('work_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routing_operations', to='core.workcentre')),
            ],
            options={
                'ordering': ['operation_sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_sequence', models.PositiveIntegerField(default=10)),
                ('operation_name', models.CharField(max_length=120)),
                ('setup_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('run_minutes_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('planned_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('READY', 'Ready'), ('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('source_routing_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_operations', to='core.routingoperation')),
                ('work_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_operations', to='core.workcentre')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.workorder')),
            ],
            options={
                'ordering': ['operation_sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='routingheader',
            index=models.Index(fields=['tenant', 'product', 'status'], name='core_routin_tenant__2a4d14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routingheader',
            unique_together={('tenant', 'routing_code')},
        ),
        migrations.AddIndex(
            model_name='workcentre',
            index=models.Index(fields=['tenant', 'site', 'is_active'], name='core_workce_tenant__b1689a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workcentre',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='routingoperation',
            unique_together={('routing', 'operation_sequence')},
        ),
    ]
