# Generated by Django 5.2.15 on 2026-06-16 13:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_alter_mrpexception_exception_code_routingheader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingoperation',
            name='subcontract_unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Service cost per unit for a subcontract operation', max_digits=12),
        ),
        migrations.AddField(
            model_name='routingoperation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_operations', to='core.supplier'),
        ),
        migrations.AlterField(
            model_name='mrpexception',
            name='exception_code',
            field=models.CharField(choices=[('SHORTAGE', 'Shortage'), ('PAST_DUE_DEMAND', 'Past-due demand'), ('PAST_DUE_SUPPLY', 'Past-due supply'), ('RESCHEDULE_IN', 'Reschedule in'), ('RESCHEDULE_OUT', 'Reschedule out'), ('CANCEL_SUPPLY', 'Cancel supply'), ('EXCESS_SUPPLY', 'Excess supply'), ('BELOW_SAFETY_STOCK', 'Below safety stock'), ('MISSING_BOM', 'Missing BOM'), ('MISSING_ROUTING', 'Missing routing'), ('MISSING_SUPPLIER', 'Missing supplier'), ('MISSING_LEAD_TIME', 'Missing lead time'), ('MISSING_UOM_CONVERSION', 'Missing UOM conversion'), ('NON_NETTABLE_STOCK', 'Non-nettable stock excluded'), ('EXPIRED_LOT', 'Expired lot'), ('CAPACITY_OVERLOAD', 'Capacity overload'), ('SALES_ORDER_REQUIRED_DATE_MISSING', 'Sales order required date inferred'), ('PURCHASE_ORDER_DUE_DATE_MISSING', 'Purchase order due date inferred'), ('PAST_DUE_RELEASE', 'Planned release date is in the past'), ('UNSUPPORTED_LOT_SIZING_METHOD', 'Unsupported lot sizing method'), ('FORECAST_VERSION_MISSING', 'Forecast version not selected'), ('FORECAST_VERSION_INVALID', 'Forecast version invalid for planning'), ('FORECAST_LINE_OUTSIDE_HORIZON', 'Forecast line outside planning horizon'), ('FORECAST_LINE_INVALID_QTY', 'Forecast line has invalid quantity'), ('UNSUPPORTED_FORECAST_CONSUMPTION_METHOD', 'Unsupported forecast consumption method'), ('FORECAST_UOM_CONVERSION_MISSING', 'Missing forecast UOM conversion'), ('FORECAST_SITE_MISSING', 'Forecast site missing'), ('INVALID_ROUTING', 'Invalid routing'), ('ROUTING_NOT_ACTIVE', 'Routing not active'), ('MISSING_WORK_CENTRE', 'Missing work centre'), ('INVALID_WORK_CENTRE', 'Invalid / inactive work centre'), ('SUBCONTRACT_OPERATION_NOT_SUPPORTED', 'Subcontract operation not supported'), ('ROUTING_DURATION_INVALID', 'Routing duration invalid'), ('MISSING_SUBCONTRACT_SUPPLIER', 'Missing subcontract supplier'), ('SUBCONTRACT_OPERATION_SUPPLIER_MISSING', 'Subcontract operation supplier missing'), ('SUBCONTRACT_CONVERSION_FAILED', 'Subcontract conversion failed'), ('SUBCONTRACT_RECEIPT_UNSUPPORTED', 'Subcontract receipt unsupported'), ('SUBCONTRACT_COST_MISSING', 'Subcontract cost missing'), ('SUBCONTRACT_ORDER_ALREADY_CONVERTED', 'Subcontract order already converted'), ('INVALID_BOM', 'Invalid BOM'), ('BOM_NOT_APPROVED', 'BOM not approved'), ('BOM_NOT_EFFECTIVE', 'BOM not effective'), ('CIRCULAR_BOM', 'Circular BOM'), ('BOM_MAX_DEPTH_EXCEEDED', 'BOM max depth exceeded'), ('MISSING_COMPONENT_PLANNING', 'Missing component planning profile'), ('PHANTOM_BOM_MISSING', 'Phantom item has no BOM'), ('MISSING_TRANSFER_SOURCE_SITE', 'Missing transfer source site'), ('INVALID_TRANSFER_SOURCE_SITE', 'Invalid transfer source site'), ('SOURCE_SITE_SHORTAGE', 'Source site shortage'), ('TRANSFER_LOOP_DETECTED', 'Transfer loop detected'), ('TRANSFER_MAX_DEPTH_EXCEEDED', 'Transfer max depth exceeded'), ('INBOUND_TRANSFER_DUE_DATE_MISSING', 'Inbound transfer due date inferred')], max_length=40),
        ),
    ]
