# Generated by Django 5.2.15 on 2026-06-16 15:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_routingoperation_subcontract_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='is_reversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reversal_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reversed_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='core.inventorymovement'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reversed_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='reversal_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scrap_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='reversed_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='scrap_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='scrapped_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIVE', 'Purchase received'), ('SALE', 'Sale fulfilled'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('ADJUSTMENT', 'Manual adjustment'), ('RETURN', 'Return from customer'), ('RETURN_SUPPLIER', 'Return to supplier'), ('DAMAGE', 'Damage'), ('WRITE_OFF', 'Write-off'), ('RESERVATION', 'Reservation'), ('RELEASE', 'Release'), ('WORK_ORDER_ISSUE', 'Work order material issue'), ('WORK_ORDER_COMPLETION', 'Work order completion'), ('WORK_ORDER_SCRAP', 'Work order material scrap'), ('WORK_ORDER_ISSUE_REVERSAL', 'Work order issue reversal'), ('WORK_ORDER_COMPLETION_REVERSAL', 'Work order completion reversal'), ('WORK_ORDER_COMPLETION_SCRAP', 'Work order finished-goods scrap')], max_length=40),
        ),
    ]
