# Generated by Django 5.2.15 on 2026-06-16 16:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_inventorymovement_is_reversal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingaccountingprofile',
            name='direct_labour_absorption_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.glaccount'),
        ),
        migrations.AddField(
            model_name='manufacturingaccountingprofile',
            name='manufacturing_overhead_absorption_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.glaccount'),
        ),
        migrations.AddField(
            model_name='workcentre',
            name='labour_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='workcentre',
            name='machine_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='workcentre',
            name='overhead_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wip_labour_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wip_overhead_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='workorderoperation',
            name='actual_labour_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='workorderoperation',
            name='actual_overhead_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='workorderoperation',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='workorderoperation',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AddField(
            model_name='workorderoperation',
            name='planned_labour_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='workorderoperation',
            name='planned_overhead_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='WorkOrderCostBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('LABOUR', 'Direct labour'), ('OVERHEAD', 'Manufacturing overhead')], max_length=10)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=10)),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.journalentry')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_bookings', to='core.workorderoperation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wo_cost_bookings', to='core.tenant')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_bookings', to='core.workorder')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['tenant', 'work_order'], name='core_workor_tenant__2ef697_idx'), models.Index(fields=['operation', 'booking_type'], name='core_workor_operati_e3e3ea_idx')],
            },
        ),
    ]
