# Generated by Django 5.2.15 on 2026-06-16 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_workcentre_finite_capacity_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MRPRescheduleSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_number', models.CharField(max_length=40)),
                ('suggestion_type', models.CharField(choices=[('CAPACITY_LEVEL', 'Capacity levelling'), ('RESCHEDULE_IN', 'Reschedule in'), ('RESCHEDULE_OUT', 'Reschedule out'), ('CANCEL_SUPPLY', 'Cancel supply'), ('EXPEDITE', 'Expedite'), ('DEFER', 'Defer')], max_length=20)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('ACCEPTED', 'Accepted'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='SUGGESTED', max_length=12)),
                ('source_type', models.CharField(choices=[('MRP_PLANNED_ORDER', 'Planned order'), ('WORK_ORDER_OPERATION', 'Work order operation'), ('PURCHASE_ORDER', 'Purchase order'), ('PURCHASE_REQUISITION', 'Purchase requisition'), ('TRANSFER_ORDER', 'Transfer order'), ('WORK_ORDER', 'Work order')], max_length=24)),
                ('source_document_type', models.CharField(blank=True, max_length=50)),
                ('source_document_id', models.CharField(blank=True, max_length=100)),
                ('source_line_id', models.CharField(blank=True, max_length=100)),
                ('current_start', models.DateField(blank=True, null=True)),
                ('current_end', models.DateField(blank=True, null=True)),
                ('suggested_start', models.DateField(blank=True, null=True)),
                ('suggested_end', models.DateField(blank=True, null=True)),
                ('current_release_date', models.DateField(blank=True, null=True)),
                ('current_receipt_date', models.DateField(blank=True, null=True)),
                ('suggested_release_date', models.DateField(blank=True, null=True)),
                ('suggested_receipt_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('impact_summary', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_suggestions_applied', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_suggestions_created', to=settings.AUTH_USER_MODEL)),
                ('mrp_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_suggestions', to='core.mrprun')),
                ('planned_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_suggestions', to='core.mrpplannedorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_suggestions', to='core.product')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_suggestions_rejected', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_suggestions', to='core.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_suggestions', to='core.tenant')),
                ('work_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_suggestions', to='core.workcentre')),
                ('work_order_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_suggestions', to='core.workorderoperation')),
            ],
            options={
                'ordering': ['severity', 'id'],
                'indexes': [models.Index(fields=['tenant', 'mrp_run', 'status'], name='core_mrpres_tenant__bc3caf_idx'), models.Index(fields=['mrp_run', 'suggestion_type'], name='core_mrpres_mrp_run_4a476d_idx')],
            },
        ),
    ]
