# Generated by Django 5.2.15 on 2026-06-16 20:49

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_mrpreschedulesuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReportView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('report_type', models.CharField(choices=[('RUN_SUMMARY', 'Run summary'), ('PLANNED_ORDERS', 'Planned orders'), ('DEMAND_SUPPLY', 'Demand vs supply'), ('SHORTAGES', 'Shortages'), ('EXCEPTIONS', 'Exceptions'), ('PEGGING', 'Pegging'), ('FORECAST_CONSUMPTION', 'Forecast consumption'), ('CAPACITY_LOAD', 'Capacity load'), ('WORK_ORDER_COST', 'Work order cost'), ('RESCHEDULE_SUGGESTIONS', 'Reschedule suggestions'), ('MRP_WORKBENCH', 'MRP workbench')], max_length=24)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('columns_json', models.JSONField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_views', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_views', to='core.tenant')),
            ],
            options={
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('report_type', models.CharField(choices=[('RUN_SUMMARY', 'Run summary'), ('PLANNED_ORDERS', 'Planned orders'), ('DEMAND_SUPPLY', 'Demand vs supply'), ('SHORTAGES', 'Shortages'), ('EXCEPTIONS', 'Exceptions'), ('PEGGING', 'Pegging'), ('FORECAST_CONSUMPTION', 'Forecast consumption'), ('CAPACITY_LOAD', 'Capacity load'), ('WORK_ORDER_COST', 'Work order cost'), ('RESCHEDULE_SUGGESTIONS', 'Reschedule suggestions'), ('MRP_WORKBENCH', 'MRP workbench')], max_length=24)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel')], default='CSV', max_length=8)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=8)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Mon .. 6=Sun (weekly)', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1-28 (monthly)', null=True)),
                ('time_of_day', models.TimeField(default=datetime.time(6, 0))),
                ('recipients', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('NEVER_RUN', 'Never run'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='NEVER_RUN', max_length=12)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_exports_created', to=settings.AUTH_USER_MODEL)),
                ('saved_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_exports', to='core.savedreportview')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_exports', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='savedreportview',
            index=models.Index(fields=['tenant', 'report_type'], name='core_savedr_tenant__c3ac49_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreportview',
            index=models.Index(fields=['owner', 'report_type'], name='core_savedr_owner_i_a68106_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreportexport',
            index=models.Index(fields=['tenant', 'is_active', 'next_run_at'], name='core_schedu_tenant__f6d5f3_idx'),
        ),
    ]
